#!/bin/bash

#PBS -N LBM
#PBS -joe
#PBS -o LBM.out
#PBS -q teaching
#PBS -l nodes=1:ppn=16,walltime=00:10:00

#! Mail to user if job aborts
#PBS -m a

#! application name
application="make run"

#! Run options for the application
options="PARAM_FILE=../inputs/box.params"

###############################################################
### You should not have to change anything below this line ####
###############################################################

#! change the working directory (default is home directory)

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following machines:
echo `cat $PBS_NODEFILE | uniq`

numnodes=`wc $PBS_NODEFILE | awk '{ print $1 }'`

export OMP_NUM_THREADS=$numnodes

#! Run the executable
$application $options
